/**
 * Template System UX P3 — five premium templates, one resumeData, separate render layers.
 */

import {
  TEMPLATE_V2_PAGE_POLICY,
  TEMPLATE_V2_IDS,
  TEMPLATE_SYSTEM_V2,
} from './contract.js';

/**
 * UX P3 canonical registry.
 * `renderLayerId` maps to layout implementation in cv-templates.js (no parser logic).
 */
export const TEMPLATE_V2_REGISTRY = Object.freeze({
  ats: {
    id: 'ats',
    displayName: 'ATS Clean',
    tagline: 'System sans · pure black & white · recruiter-readable',
    renderLayerId: 'ats',
    layoutFamily: 'single',
    atsSafety: 'high',
    creativeLevel: 1,
    defaultSpacing: 'normal',
    cssClass: 'template-ats',
    category: 'ATS',
    bestFor: 'Applicant tracking systems · corporate roles',
    sections: ['experience', 'education', 'skills', 'tools', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'editorial-magazine': {
    id: 'editorial-magazine',
    displayName: 'Editorial Magazine',
    tagline: 'Magazine cover · Kinfolk · Wallpaper* · Monocle hierarchy',
    renderLayerId: 'editorial-magazine',
    layoutFamily: 'magazine',
    atsSafety: 'medium',
    creativeLevel: 5,
    defaultSpacing: 'normal',
    cssClass: 'template-editorial-magazine',
    category: 'Editorial',
    bestFor: 'Kinfolk · Wallpaper* · Aesop · Monocle · culture',
    sections: ['experience', 'education', 'skills', 'tools', 'clients', 'projects', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'startup-builder': {
    id: 'startup-builder',
    displayName: 'Startup Builder',
    tagline: 'Traction strip · impact split · founder narrative',
    renderLayerId: 'startup-builder',
    layoutFamily: 'split',
    atsSafety: 'high',
    creativeLevel: 3,
    defaultSpacing: 'normal',
    cssClass: 'template-startup-builder',
    category: 'Startup',
    bestFor: 'Founders · operators · venture-backed roles',
    sections: ['traction', 'experience', 'skills', 'tools', 'education', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'art-director-portfolio': {
    id: 'art-director-portfolio',
    displayName: 'Art Director Portfolio',
    tagline: 'Luxury portfolio document · hero · press · platform links',
    renderLayerId: 'art-director-portfolio',
    layoutFamily: 'magazine',
    atsSafety: 'medium',
    creativeLevel: 5,
    defaultSpacing: 'normal',
    cssClass: 'template-art-director-portfolio',
    category: 'Creative',
    bestFor: 'Art directors · luxury campaigns · Behance · Dribbble',
    sections: ['clients', 'projects', 'awards', 'press', 'experience', 'education', 'portfolioLinks'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'visual-timeline': {
    id: 'visual-timeline',
    displayName: 'Visual Timeline',
    tagline: 'Vertical career spine · Apple keynote minimalism',
    renderLayerId: 'visual-timeline',
    layoutFamily: 'single',
    atsSafety: 'high',
    creativeLevel: 3,
    defaultSpacing: 'normal',
    cssClass: 'template-visual-timeline',
    category: 'Timeline',
    bestFor: 'Career arc · connected clients & projects',
    sections: ['experience', 'clients', 'projects', 'education', 'skills', 'tools', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'swiss-editorial': {
    id: 'swiss-editorial',
    displayName: 'Swiss Editorial',
    tagline: 'Neue Grafik grid · Monocle rhythm · FT sophistication',
    renderLayerId: 'swiss-editorial',
    layoutFamily: 'split',
    atsSafety: 'high',
    creativeLevel: 3,
    defaultSpacing: 'normal',
    cssClass: 'template-swiss-editorial',
    category: 'Editorial',
    bestFor: 'Swiss design · editorial · consulting · culture',
    sections: ['summary', 'experience', 'education', 'skills', 'tools', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'executive-luxury': {
    id: 'executive-luxury',
    displayName: 'Executive Luxury',
    tagline: 'McKinsey minimalism · impact metrics · leadership hierarchy',
    renderLayerId: 'executive-luxury',
    layoutFamily: 'single',
    atsSafety: 'high',
    creativeLevel: 2,
    defaultSpacing: 'normal',
    cssClass: 'template-executive-luxury',
    category: 'Executive',
    bestFor: 'McKinsey · BCG · Goldman Sachs · C-suite',
    sections: ['summary', 'experience', 'achievements', 'education', 'skills', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'ats-elite': {
    id: 'ats-elite',
    displayName: 'ATS Elite',
    tagline: 'Dense black & white · Google · Stripe · Linear · interview-ready',
    renderLayerId: 'ats-elite',
    layoutFamily: 'single',
    atsSafety: 'high',
    creativeLevel: 1,
    defaultSpacing: 'normal',
    cssClass: 'template-ats-elite',
    category: 'ATS',
    bestFor: 'Google · Stripe · Linear · Notion · senior hiring',
    sections: ['summary', 'experience', 'education', 'skills', 'tools', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  creative: {
    id: 'creative',
    displayName: 'Creative Portfolio',
    tagline: 'Bold typography · clients & projects first',
    renderLayerId: 'creative',
    layoutFamily: 'magazine',
    atsSafety: 'medium',
    creativeLevel: 4,
    defaultSpacing: 'normal',
    cssClass: 'template-creative',
    category: 'Creative',
    bestFor: 'Designers · illustrators · art directors',
    sections: ['clients', 'projects', 'portfolioLinks', 'software', 'experience', 'skills'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'creative-director': {
    id: 'creative-director',
    displayName: 'Creative Director',
    tagline: 'Kinfolk editorial · selected clients & projects · luxury whitespace',
    renderLayerId: 'creative-director',
    layoutFamily: 'magazine',
    atsSafety: 'medium',
    creativeLevel: 5,
    defaultSpacing: 'normal',
    cssClass: 'template-creative-director',
    category: 'Creative',
    bestFor: 'Creative directors · illustrators · Nike · Adobe · Apple',
    sections: ['clients', 'projects', 'experience', 'skills', 'tools', 'education'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'executive-minimal': {
    id: 'executive-minimal',
    displayName: 'Executive Minimal',
    tagline: 'Centered serif · stone palette · compact senior profile',
    renderLayerId: 'executive-minimal',
    layoutFamily: 'single',
    atsSafety: 'high',
    creativeLevel: 2,
    defaultSpacing: 'compact',
    cssClass: 'template-executive-minimal',
    category: 'Executive',
    bestFor: 'Leadership · consulting · dense profiles',
    sections: ['experience', 'education', 'skills', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  'modern-two-column': {
    id: 'modern-two-column',
    displayName: 'Tech Resume',
    tagline: 'Dark skills rail · mono identity · product & engineering',
    renderLayerId: 'modern-two-column',
    layoutFamily: 'split',
    atsSafety: 'high',
    creativeLevel: 2,
    defaultSpacing: 'normal',
    cssClass: 'template-modern-two-column',
    category: 'Modern',
    bestFor: 'Tech · product · skills-forward profiles',
    sections: ['experience', 'education', 'skills', 'tools', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
  editorial: {
    id: 'editorial',
    displayName: 'Modern Editorial',
    tagline: 'Magazine layout · luxury feel · ATS-readable',
    renderLayerId: 'editorial',
    layoutFamily: 'split',
    atsSafety: 'high',
    creativeLevel: 3,
    defaultSpacing: 'normal',
    cssClass: 'template-editorial',
    category: 'Editorial',
    bestFor: 'Luxury · culture · senior creative roles',
    sections: ['experience', 'clients', 'projects', 'skills', 'tools', 'languages'],
    pagePolicy: TEMPLATE_V2_PAGE_POLICY,
  },
});

/** Legacy / marketing aliases → UX P3 canonical id. */
export const TEMPLATE_V2_ALIASES = Object.freeze({
  ats: 'ats',
  'ats-elite': 'ats-elite',
  'executive-luxury': 'executive-luxury',
  'executive-luxury-template': 'executive-luxury',
  'swiss-editorial': 'swiss-editorial',
  'swiss-editorial-template': 'swiss-editorial',
  'visual-timeline': 'visual-timeline',
  'visual-timeline-template': 'visual-timeline',
  timeline: 'visual-timeline',
  'ats-clean': 'ats',
  'modern-clean': 'ats',
  creative: 'creative',
  'creative-portfolio': 'creative',
  creativedirector: 'creative-director',
  'creative-director': 'creative-director',
  pentagram: 'creative',
  artdirector: 'art-director-portfolio',
  'art-director': 'art-director-portfolio',
  'art-director-portfolio': 'art-director-portfolio',
  'startup-builder': 'startup-builder',
  founder: 'startup-builder',
  startup: 'startup-builder',
  agencyportfolio: 'creative',
  'agency-portfolio': 'creative',
  portfolio: 'creative',
  modernportfolio: 'creative',
  premium: 'creative',
  'executive-minimal': 'executive-minimal',
  executive: 'executive-minimal',
  minimal: 'executive-minimal',
  minimaliste: 'executive-minimal',
  compact: 'executive-minimal',
  compactrecruiter: 'executive-minimal',
  'classic-executive': 'executive-minimal',
  'executive-board': 'executive-minimal',
  corporate: 'executive-minimal',
  'modern-two-column': 'modern-two-column',
  'two-column': 'modern-two-column',
  sidebar: 'modern-two-column',
  productdesigner: 'modern-two-column',
  consultingelite: 'modern-two-column',
  consulting: 'modern-two-column',
  strategy: 'modern-two-column',
  editorial: 'editorial',
  swiss: 'swiss-editorial',
  'swiss-editorial': 'swiss-editorial',
  swisspro: 'swiss-editorial',
  freelance: 'executive-minimal',
});

/**
 * @param {string} [id]
 * @returns {import('./contract.js').TemplateV2Contract & { id: string }}
 */
export function resolveTemplateV2(id) {
  const key = String(id || 'ats')
    .trim()
    .toLowerCase();
  const canonical = TEMPLATE_V2_ALIASES[key] || (TEMPLATE_V2_REGISTRY[key] ? key : 'ats');
  return TEMPLATE_V2_REGISTRY[canonical] || TEMPLATE_V2_REGISTRY.ats;
}

/**
 * @param {string} [id]
 * @returns {string}
 */
export function resolveTemplateV2RenderLayer(id) {
  return resolveTemplateV2(id).renderLayerId;
}

export const TEMPLATE_V2_COUNT = TEMPLATE_V2_IDS.length;
export const TEMPLATE_V2_ENGINE = TEMPLATE_SYSTEM_V2;
